name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Change to the right directory
        run: cd lab6   # Correct path to the Makefile

      - name: Run Makefile
        run: make

      - name: Run Executable
        run: ./hello
