name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Change to the right directory
        run: cd devops/Lab6

      - name: List Files
        run: ls  # This command lists the files in the directory for debugging

      - name: Run Makefile
        run: make

      - name: run executable
        run: ./hello
