name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Change to the right directory
        run: cd devops/lab6   # Correct path to the Makefile

      - name: List Files
        run: ls  # This command lists the files in the directory for debugging

      - name: Run Makefile
        run: make
